kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    reloader.stakater.com/search: "true"
  name: shared-qa-simple-cicd-for-go
  namespace: qa-paas-sre
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: shared-qa-simple-cicd-for-go
  template:
    metadata:
      labels:
        app: shared-qa-simple-cicd-for-go
      annotations:
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
        deployment.application.cd/change_id: ""
        deployment.application.cd/env: qa
        deployment.application.cd/region: CNE2
        deployment.application.cd/subscription: Shared
        deployment.application.cd/version: v20210713173450
        deployment.application.metadata/app-component: simple-cicd-for-go
        deployment.application.metadata/application: paas-sre-toolkit
        deployment.application.metadata/domain: PaaS
        deployment.application.metadata/git-branch: ""
        deployment.application.metadata/git-commit: ""
        deployment.application.metadata/git-url: ""
        deployment.application.metadata/use_vault: ""
    spec:
      containers:
        - name: shared-qa-simple-cicd-for-go
          image: ***.azurecr.cn/paas-sre-toolkit/simple-cicd-for-go:v20210713173450
          imagePullPolicy: Always
          volumeMounts:
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 360 ## equals to the maximum startup time of the application + couple of seconds
            periodSeconds: 30
            timeoutSeconds: 20
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60 ## equals to minimum startup time of the application
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              cpu: "1000m"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"
          env:
            - name: FORCE_REDEPLOY
              value: ''
            - name: CONSUL_ADDR
              value: ''
            - name: profile
              value: qa
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: "***"
      volumes:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: 'app'
                      operator: In
                      values:
                        - shared-qa-simple-cicd-for-go
                topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  -  {key: nodeType, operator: In, values: ["slave"]}
                  -  {key: for-slave, operator: In, values: ["true"]}

---
apiVersion: v1
kind: Service
metadata:
  name: shared-qa-simple-cicd-for-go
  namespace: qa-paas-sre
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: shared-qa-simple-cicd-for-go